Unity-Technologies/UnityRenderStreaming

- Packages/com.unity.renderstreaming/package.json
- Packages/com.unity.template.renderstreaming/package.json
Official name of the packages is **Unity Render Streaming**.
For that reason I modified `package.json`.
Please tell me if you find wrong names.
> chore: fixed package name to "Unity Render Streaming"

- Packages/com.unity.renderstreaming/Editor/RenderStreamingMenu.cs
`EditorUtility.DisplayCancelableProgressBar` returns `true` when pushed cancel button on the progress window.
> fix: Fixed downloading process for webapp

- Packages/com.unity.webrtc/Third Party Notices.md
WebRTC package doesn't depend on `fft` and `fft4g`.
I removed licenses of two libraries from `Third Party Notices.md` .
Fix [`build_libwebrtc.cmd`](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/release/1.1.0/build_libwebrtc.cmd) to remove `fft` and `fft4g` headers from `webrtc-win.zip`
> chore: Remove unused licenses

- Assets/Scripts/SimpleCameraController.cs
Fixed issue #138. 
- `u` key assignment is reset camera position to initial one
> feat: Add keyboard event to reset camera position

- Assets/Scripts/RemoteInput.cs
- Assets/Scripts/SimpleCameraController.cs
- Assets/Scripts/UIController.cs
- Got wrong touch position when detects multi-touch
- Sometimes `TouchPhase.End` touch events aren't detected on the browser
- We need to force change touch status to `TouchPhase.End`
- But it didn't set position when force change touch status
- Fixed to set the previous position to the touch event
> fixed: Fixed bugs that receive wrong position when detect multi-touch

- Assets/Scripts/Editor/RenderStreamingEditor.cs
- Assets/Scripts/RenderStreaming.cs
This patch allows for passing the signaling URL and a ICE JSON url via command line argument.
The JSON returned by the URL is generated to work with coTURN in the form of:
```json
{
"lifetimeDuration": "86400s",
"iceServers": [
{
"urls": [
"stun:1.2.3.4:3478"
]
},
{
"urls": [
"turn:1.2.3.4:3478?transport=udp"
],
"username": "1572994870-user@example.com",
"credential": "some-base64-hmac-sha1-generated-credential"
}
],
"blockStatus": "NOT_BLOCKED",
"iceTransportPolicy": "all"
}
```
> add standalone player command line args for ICE JSON url and signaling

- WebApp/public/scripts/signaling.js
This patch lets the signaling web server run behind a proxy with a url prefix other than "/".
> add location path name to signaling path

- Packages/com.unity.renderstreaming/Samples~/HDRP/Editor/RenderStreamingHDRPAutomator.cs
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/164
> fix: handle read only attributes when importing HDRP sample

- .yamato/upm-ci-publish-github-release.yml
- .yamato/upm-ci-template.yml
- Packages/com.unity.template.renderstreaming/package.json
- Packages/manifest.json
- Fixed mismatch of HDRP version 
- Fixed mismatch of Render Streaming version 
- Removed unused dependencies
> chore: fixed build process for template project

- WebApp/public/scripts/app.js
- WebApp/public/scripts/register-events.js
- WebApp/public/scripts/video-player.js
- WebApp/public/stylesheets/style.css
- com.unity.template.renderstreaming-hd/Assets/Scenes/samplescene.unity
- com.unity.template.renderstreaming-hd/Assets/Scripts/AudioStreamer.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/CameraStreamer.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/CameraStreamer.cs.meta
- com.unity.template.renderstreaming-hd/Assets/Scripts/Editor/RenderStreamingEditor.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/RenderStreaming.cs
This is a demonstration of the multi-camera feature that is available to stream multiple videos.
- Implemented `CameraStreamer` class to set parameters for each video stream track.
- Changed `executionOrder` of `RenderStreaming` class to finish initialization earlier than others
- Added the process about the message from Unity to browser to tell which streams select for displaying the main video.
> feat: add second-camera

- com.unity.template.renderstreaming-hd/Assets/Scripts/Editor/RenderStreamingEditor.cs
Fixed the broken `Render Streaming` Inspector
> fix: Render Sreaming inspector layout

- WebApp/public/scripts/register-events.js
- com.unity.template.renderstreaming-hd/Assets/Scripts/RemoteInput.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/UIController.cs
Remove unused byte array contained in a message of the gamepad event.
||byte length|start offset|
|--|--|--|
|eventtype|1|0|
|datetime|8|1|
|gamepadEventType|1|9|
|buttonIndex|1|10|
|value|8|11|
||byte length|start offset|
|--|--|--|
|eventtype|1|0|
|gamepadEventType|1|1|
|buttonIndex|1|2|
|value|8|3|
Remove unused member in `UIContoller` class
> fix: fixed byte array layout of the message for gamepad

- com.unity.template.renderstreaming-hd/Packages/com.unity.template.renderstreaming-hd/package.json
- com.unity.template.renderstreaming-rtx/Packages/com.unity.template.renderstreaming-rtx/package.json
Before this PR, a display name is too long so the layout on the Unity hub is broken.
> chore: rename display name

- .yamato/meta/environments.yml
- .yamato/promotion.yml
- .yamato/upm-ci-renderstreaming-packages.yml
- .yamato/upm-ci-renderstreaming-unitypackage.yml
- .yamato/upm-ci-template.yml
This fix is for updating the yaml of Yamato because the upm registry URL is changed.
> chore: Update yaml to replace upm registry

- .yamato/meta/environments.yml
- .yamato/upm-ci-publish-github-release.yml
- .yamato/upm-ci-template.yml
Fixed the job that publishes packages to GitHub Release.
- Exclude dependency job that unstable template test   
- Remove artifacts that occur build error
> fix: fixed yaml to publish the packages on GitHub Release

- .yamato/upm-ci-publish-github-release.yml
- .yamato/upm-ci-webapp.yml
- com.unity.renderstreaming/Editor/WebAppDownloader.cs
- pack_webapp.sh
- pack_webapp_mac.sh
Rename appname on macos and release each binary.
Issue: https://github.com/Unity-Technologies/UnityRenderStreaming/issues/305
> fix: divide webapp release mac

- com.unity.template.renderstreaming-hd/Assets/Scripts/RemoteInput.cs
Pressing the multiple keys simultaneously recognize only one of them.
The cause of the issue is clearing the previous state of the keyboard when receive new input.
In this changes, the previous state of keyboard is kept.
So if received new input, merges it to previous state.
> fix: pressing multiple buttons on a keyboard do not work well

- com.unity.renderstreaming/Editor/RenderStreamingMenu.cs
- com.unity.renderstreaming/Editor/WebAppDownloader.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/FurioosSignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/HttpSignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/ISignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/SignalingMessage.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/WebSocketSignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Tests/Editor.meta
- com.unity.template.renderstreaming-hd/Assets/Tests/Editor/RenderStreamingTemplateEditorTest.cs
- com.unity.template.renderstreaming-hd/Assets/Tests/Editor/RenderStreamingTemplateEditorTest.cs.meta
- com.unity.template.renderstreaming-hd/Assets/Tests/Editor/Unity.Template.RenderStreaming.EditorTests.asmdef
- com.unity.template.renderstreaming-hd/Assets/Tests/Editor/Unity.Template.RenderStreaming.EditorTests.asmdef.meta
- com.unity.template.renderstreaming-hd/Assets/Tests/Runtime/SignalingTest.cs
- com.unity.template.renderstreaming-hd/Assets/Tests/Runtime/SignalingTest.cs.meta
- com.unity.template.renderstreaming-hd/Assets/Tests/Runtime/Unity.Template.RenderStreaming.RuntimeTests.asmdef
This PR fixes the issue occurred when signaling server using websocket.
By the issue, signaling is not work well. Even if using TURN server, video stream can not arrive another peer.
- The signaling client had the bug: When the client received the "candidate" message, a callback was not fired.
- Add unittests to reproduce the issue.
- Add signaling test running on CI after the package com.unity.renderstreaming upgrade 2.2.0.
> fix: Fix an issue of the signaling client  

- WebApp/public/scripts/video-player.js
- com.unity.template.renderstreaming-hd/Assets/Scripts/CameraStreamer.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/RenderStreaming.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/WebCamStreamer.cs
Related issues.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/182
https://github.com/Unity-Technologies/com.unity.webrtc/issues/183
In this pull request, removed codes which make customized SDPs to change bitrate.
To customize SDPs happens unexpected results like the bitrate become unstable.
> fix : Stop editing SDP to custom bitrate

- .yamato/upm-ci-template.yml
Template testing on Yamato is not work correctly, so remove the trigger of the template test until it will be fixed.
> chore: remove CI trigger of the template test

- com.unity.template.renderstreaming-hd/Assets/Scripts/UIController.cs
This PR is created to avoid the exception.
This NullPointerException occurred when `UIController` instance is not attached `SimpleCameraController` component.
```
NullReferenceException: Object reference not set to an instance of an object
Unity.RenderStreaming.UIController.FixedUpdate () (at Assets/Scripts/UIController.cs:48)
```
> fix: Fix UI controller error

- WebApp/public/scripts/video-player.js
Currently, this code is no needed. `RTCDataChannel` work fine on iOS 14.
Maybe this code is needed on old iOS version ( 11/12... )
Related Issue: https://github.com/Unity-Technologies/UnityRenderStreaming/issues/340
> chore: remove microphone access prompt on safari

- com.unity.renderstreaming/Runtime/Scripts/RemoteInput.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/ISignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
- com.unity.renderstreaming/Tests/Runtime/ConditionalIgnore.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RemoteInputTest.cs
- com.unity.renderstreaming/Tests/Runtime/RemoteInputTest.cs.meta
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingTest.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling.meta
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs.meta
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/TestUtility.cs
- com.unity.renderstreaming/Tests/Runtime/Unity.RenderStreaming.RuntimeTests.asmdef
`MockSignaling` class is for simulating communication between peers for unit-testing.
Until this change, we have needed to launch the server process to run unit-testing, but now we only need to use this mock class.
> test: Add MockSignaling class to simulate the signaling behavior for testing

- .yamato/upm-ci-renderstreaming-packages.yml
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
HttpSignalingTest faild only on Yamato
mac still can't be enabled because setup use metal on yamato
> Fix: enable Linux SignalingTest only websockeet signaling

- com.unity.renderstreaming/Runtime/AssemblyInfo.cs
- com.unity.renderstreaming/Runtime/AssemblyInfo.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs.meta
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs.meta
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
Added `RenderStreamingInternal` class (This class name might be changed to a better one) to improve the testability of `RenderStreaming` class.
In the past, there is not a test of `RenderStreaming` class, because for two reasons.
- `RenderStreaming` class inherits `MonoBehaviour` class
- Testing of `RenderStreaming` needs to run the Signaling server
After this change, I will refactor `RenderStreaming` class to use `RenderStreamingInternal` class.
> refactor: Add `RenderStreamingInternal`

- com.unity.renderstreaming/Runtime/Scripts/Signaling/FurioosSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
This change is for removing `CS0067` warning in `FurioosSignaling` class
> fix: Remove CS0067 warning in FurioosSignaling class

- .yamato/meta/environments.yml
- .yamato/upm-ci-renderstreaming-packages.yml
- .yamato/upm-ci-template.yml
- .yamato/upm-ci-webapp.yml
- BuildScripts~/template/remote.sh.template
- BuildScripts~/test_package_mac.sh
- RenderStreaming~/ProjectSettings/ProjectSettings.asset
- com.unity.renderstreaming/Runtime/Unity.RenderStreaming.Runtime.asmdef
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/Unity.RenderStreaming.RuntimeTests.asmdef
- Enabled ci on macos/ios
- `remote.sh.templete` and `test_package_mac.sh` refer webrtc package https://github.com/Unity-Technologies/com.unity.webrtc/tree/develop/BuildScripts~
- Notice: signaling test ignore on ios device test
- add trigger job for (package/template/webapp) test
> chore: run CI testing on macOS/iOS

- .yamato/meta/environments.yml
- .yamato/upm-ci-publish-github-release.yml
- .yamato/upm-ci-renderstreaming-packages.yml
- .yamato/upm-ci-webapp.yml
`TEST_TARGET` variable should be `ios` or `macos`.
https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/BuildScripts~/template/remote.sh.template#L8
> chore: Enable test for standalone il2cpp on mac

- WebApp/public/videoplayer/js/main.js
Not working fullscreen button on iOS 14 Safari. (it's working on iPad OS)
If it can't be full screen, 
Changed to show Player on whole Canvas.
> Fix: fullscreen button on ios

- com.unity.renderstreaming/Tests/Runtime/InputRemotingTest.cs
Add workaround for getting failed CI test.
We should fix it but the reason for the error has not clear yet.
```
name: Unity.RenderStreaming.RuntimeTest.InputRemotingTest.AddDevice
result: FAILED
message: Unhandled log message: '[Error] Already received device with id 1 (layout 'Keyboard', description 'Keyboard (OSX)) from remote 0'. Use UnityEngine.TestTools.LogAssert.Expect
```
> fix: Exclude test to avoid unit-test error

- .yamato/upm-ci-publish-github-release.yml
Replaced to `github cli` for a tool to upload binaries to the github release page.
https://github.com/cli/cli
> chore: Replace `github-release-cli` to `gh`

- com.unity.renderstreaming/Editor/WebAppDownloader.cs
Fix this issue
https://issuetracker.unity3d.com/product/unity/issues/guid/1286452
We had got errors below.
```
Unity.RenderStreaming.Editor.WebAppDownloader:DownloadWebApp(String, String, Action`1) (at Packages/com.unity.renderstreaming/Editor/WebAppDownloader.cs:126)
Unity.RenderStreaming.Editor.<>c:<DownloadWebAppFromMenu>b__0_0(String) (at Packages/com.unity.renderstreaming/Editor/RenderStreamingMenu.cs:13)
Unity.RenderStreaming.Editor.<>c__DisplayClass13_0:<GetPackageVersion>b__0(Request`1) (at Packages/com.unity.renderstreaming/Editor/WebAppDownloader.cs:146)
Unity.RenderStreaming.Editor.RequestJob`1:OnSuccess() (at Packages/com.unity.renderstreaming/Editor/RequestJob.cs:104)
Unity.RenderStreaming.Editor.RequestJob`1:Update() (at …
```
> fixed: Fixed edtior menu

- RenderStreaming~/Packages/packages-lock.json
- com.unity.renderstreaming/CHANGELOG.md
- com.unity.renderstreaming/Runtime/Scripts/CameraStreamer.cs
- com.unity.renderstreaming/Runtime/Scripts/WebBrowserInputChannelReceiver.cs
- com.unity.renderstreaming/package.json
- Upgrade WebRTC package version 2.3.3
- Changed `antiAliasing` in `CameraStreamer` class default value to `1`
- Fixed `NullPointerException` on UnityEditor when reloading a web browser
> fix: Fixed webbrowserinput bugs

- com.unity.renderstreaming/Editor/CameraStreamerEditor.cs
- com.unity.renderstreaming/Editor/CameraStreamerEditor.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/CameraStreamer.cs
If targettexture is set on camera component, use it first
However, the color formats that can be used are limited, so check it and change it if necessary.
Implemented a custom inspector for notes
> feat: camera streamer use camera component target texture first

- com.unity.renderstreaming/Samples~/Example/Gyro/Unity.RenderStreaming.GyroSample.asmdef
- com.unity.renderstreaming/Samples~/Example/Gyro/Unity.RenderStreaming.GyroSample.asmdef.meta
This compile error occurs when importing the package sample
```
Assets\Samples\Unity Render Streaming\3.0.0-preview.1\Example\Gyro\GyroSample.cs(5,31): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
```
> fix: Compile error when importing the package sample

- com.unity.renderstreaming/Documentation~/faq.md
- com.unity.renderstreaming/Documentation~/samples.md
- com.unity.renderstreaming/Documentation~/signalingprotocol.md
- com.unity.renderstreaming/Documentation~/turnserver.md
- com.unity.renderstreaming/Documentation~/tutorial.md
The document for customizing signaling protocol had published but this is not supported right now.
In near future, we should make a new sample to show how to customize it.
> doc: Remove docs for customizing the signaling protocol

- com.unity.renderstreaming/Runtime/Scripts/Signaling/FurioosSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
It is too long time to dispose of the signaling instance because of waiting for the worker thread and the WebSocket instance.
> fix: Not waiting for the thread when disposing the signaling instance 

- WebApp/public/bidirectional/js/sendvideo.js
- com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
- rename `sldGetBackStable` to `maikingAnswer`
- keep only one process about `setLocalDescription` and `setRemoteDescription`
- ignore offer if `makingAnswer` is true, because that's offer is already receiving.
> fix: unittest and negotiation process

- .yamato/upm-ci-renderstreaming-packages.yml
In the current situation, the Yamato CI has issues that connecting the ios device is failed.
So this pull request removes the auto testing process for the ios platform for a workaround.
> chore: [workaround] Remove auto-testing for ios platform on CI

- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputRemoting.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/Receiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/Sender.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystemChannelReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystemChannelSender.cs
When transferring between scenes while streaming video, the error occurs below.
The issue is caused by remaining resources when ending the scene.
```
Assertion failed on expression: 'gCurrentManagedTempMem != NULL' UnityEngine.StackTraceUtility:ExtractStackTrace () 
Unity.Collections.NativeArray`1<ulong>:Allocate (int,Unity.Collections.Allocator,Unity.Collections.NativeArray`1<ulong>&) (at /Users/bokken/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:87) 
Unity.Collections.NativeArray`1<ulong>:.ctor (int,Unity.Collections.Allocator,Unity.Collections.NativeArrayOptions) (at /Users/bokken/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:44) 
UnityEngine.InputSystem.InputSystem:RemoveDevice (UnityEngine.InputSystem.InputDevice) …
```
> fix: Fixed errors when disposing the scene while streaming video

- WebApp/public/bidirectional/js/peer.js
- WebApp/public/bidirectional/js/sendvideo.js
- com.unity.renderstreaming/Runtime/Scripts/IRenderStreamingHandler.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Runtime/Scripts/SingleConnection.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- working bidirectional sample on web browser and unity
- add `AddTransceiver(MediaStreamTrack)`  method on RenderStreamingInternal
- change argument that add `RTCRtpTransceiverDirection` about `AddTransceiver` method 
- use `addTrack` method on webclient (before use `addTranceiver` method)
- use `AddTransceiver` method on `SingleConnection` class.
I think we should use `AddTransceiver` if we have decided on the transceiver we need.
We should use `AddTrack` when transceiver is changing dynamically.
> Fix: fix bidirectional sample

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamer.cs
`AudioStreamer` component uses `OnAudioFilterRead` method to get audio buffers and `sampleRate` parameter is needed to stream buffers. 
`sampleRate` is determined by the `AudioClip` but `AudioClip` doesn't exist when using `AuidoListener`.
> fix: Fix AudioStreamer bug

- com.unity.renderstreaming/Editor/RenderStreamingEditor.cs
Fixed the conflict between the PR and the develop branch.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/537
- Added the ability to list ISignaling child classes in the whole project (this will be important for next version of Furioos connection)
- Included the UUID function to avoid external js import
- Added "Renderstreaming on Furioos" tutorial in documentation
> feat: Better ISignaling listing + improvment + doc

- WebApp/client/public/js/sender.js
InputSystem sends two events at the same time when pressing keyboard. This fix for browser-side is according this specification.
> fix: Fix timing of sending TextEvent when pressing keyboard

- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
Remove these warning logs.
```
warning CS0168: The variable 'e' is declared but never used
```
> fix: Remove warning CS0168

- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
This PR fixes the bug that the event of disconnect from other peer is fired at unintended timing.
This situation in almost case, to use `OnConnectionStateChange` is better than `OnIceConnectionChange`.
> fix: Fixed the timing of firing connect/disconnect event 

- com.unity.renderstreaming/Editor/CameraStreamSenderEditor.cs
- com.unity.renderstreaming/Editor/PropertyDrawers.meta
- com.unity.renderstreaming/Editor/PropertyDrawers/RenderTextureDepthBufferDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/RenderTextureDepthBufferDrawer.cs.meta
- com.unity.renderstreaming/Editor/PropertyDrawers/RenderTexureAntiAliasingDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/RenderTexureAntiAliasingDrawer.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/CameraStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/ScreenStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
Added `PropertyDrawer` for `RenderTextureAntiAliacing` and `RenderTextureDepthBuffer`.
> fix: Fixed ScreenStreamSender inspector UI

- com.unity.renderstreaming/Samples~/Example/Multiplay/MultiplaySample.cs
Error occur only on Unity 2019.
This implementation is same as `GetFirstActiveToggle` method on Unity 2020
> Chore : fix compile error on unity2019

- com.unity.renderstreaming/Samples~/Example/Multiplay/Multiplay.cs
- com.unity.renderstreaming/Samples~/Example/Multiplay/MultiplayChannel.cs
`UnityEvent` is not allocated automatically on Unity2019.4. This behavior is not same with Unity2020 or later.
> fix: Fixed error in Multiplay sample on Unity2019

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Samples~/Example/Multiplay/Multiplay.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
Related issue #506, #462 
There was a bug that tracks are leaked when disposing peers in Render Streaming.
This fix is removing tracks when firing peer disconnection event.
> fix: Fix resource leak of sender track 

- RenderStreaming~/Assets/InputSystem.inputsettings.asset
- RenderStreaming~/Assets/InputSystem.inputsettings.asset.meta
Related [this document](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/com.unity.renderstreaming/Documentation~/use-inputsystem.md).
We need to config the InputSystem when we use input devices in Unity Render Streaming.
The Unity project under the `RenderStreaming~` folder is used for testing samples by developers. This pull request save trouble of having to config themselves when they test samples.
> test: Add InputSystem settings file for testing

- WebApp/client/public/js/signaling.js
- WebApp/client/test/signaling.test.js
Bugs: The current connection list was managed by an object
before `currentConnections` manage Object ( example `{connectionId: "12345"}`)
after only `connectionId` managed.
`dispatchEvent` argument change because `deleteConnection` contain only `connectionId`.
> Fix: delete connection process on httpsignaling

- com.unity.renderstreaming/Runtime/Scripts/ScreenStreamSender.cs
- Fixed streaming size by inspector
if streaming size is FullHD (1920, 1080) , crash application using hardware encoder.
todo:
- add preset on inspector
- add warning if using free form
> fix: Avoid crash if using specified Screen resolution

- com.unity.renderstreaming/Runtime/Scripts/ScreenStreamSender.cs
Bugs: can't write into rendertexture if using `BGRA32` format on Unity 2019 Windows.
Writing rendertexture format fixed `RenderTextureForamt.Default`
and always use Blit for convert texture format.
> Fix: fix screenstream sender on Unity 2019 Win

- .yamato/meta/environments.yml
- .yamato/upm-ci-renderstreaming-packages.yml
At the moment, this package is testing on the Unity Editor version 2021.2 but have been unstable yet.
This pull request excludes version 2021.2 from the editor version list of testing for publishing the package.
> chore: Exclude editor version 2021.2 from version list for testing

- com.unity.renderstreaming/Runtime/Scripts/Signaling/FurioosSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
Fix this issue https://github.com/Unity-Technologies/UnityRenderStreaming/issues/526
Need call close method on stop.
> Fix: close websocket instance when called stop

- WebApp/client/public/js/inputdevice.js
See context in issue #619.
This change bases the current key state array on the previous key state array, if there is one.  This allows multiple keys to be sent as input simultaneously, rather than only one at a time as was the previous limitation.
> Let multiple keys be held at once

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamReceiver.cs
- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
- com.unity.renderstreaming/Samples~/Example/Receiver/ReceiverSample.cs
This change is for handling the API changes of `AudioStreamTrack` which contained in the new version of WebRTC package.
> fix: Add the AudioStreamReceiver.SetSource method to receive streaming audio 

- com.unity.renderstreaming/Runtime/Scripts/InputPositionCorrector.cs
- com.unity.renderstreaming/Runtime/Scripts/InputPositionCorrector.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/InputSender.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/Receiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/Sender.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamReceiverBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/Broadcast.unity
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Samples~/Example/Receiver/ReceiverSample.cs
Related issue #454
This change fix the gap of the input position (mouse, touchscreen).
Added `InputPositionCorrector` class for correcting the position between two coordinate systems.
The process of correction is ran once on the sender side and the receiver side.
> fix: Add InputPositionCorrector class to correct the input position

- RenderStreaming~/Packages/packages-lock.json
- com.unity.renderstreaming/Samples~/Example/Broadcast/SimpleCameraControllerV2.cs
- com.unity.renderstreaming/package.json
Unity Render Streaming package depends on Input System, and have used the version 1.0.2. 
The latest version 1.3.0 is released last December, so we needed to follow the updating.
> chore: Update Input System package version 1.3.0

- RenderStreaming~/ProjectSettings/AudioManager.asset
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/MicrophoneStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/Broadcast.unity
The `AudioStreamSender` class can stream audio from the audio source. The component type as an audio source is able to use `AudioSource` or `AudioListener`. Developers can use the class by attaching these components to the same `GameObject`.
> refactor: Remove AudioSource member from AudioStreamSender class

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
Fix two issues in this pull request.
- Catch the `NullReferenceException` thrown from `AudioStreamTrack.SetData` when destroying the `RenderStreaming` component.
- Fix `NullReferenceException` when closing the scene after occurring the unexpected disconnection with web server.
> fix: Add workaround for avoiding NullReferenceException from AudioAtreamSender.SetData

- WebApp/client/public/js/sender.js
Since InputSystem 1.3, `FastMouse` type is used instead of `Mouse` for the mouse device. However, when the `layoutVariants` is not null or empty, InputSystem create `Mouse`, not `FastMouse`. 
There is a difference that the way of computing the delta value of input event between `Mouse` and `FastMouse`. So we need to force to use `FastMouse` for the mouse device.
> fix: The delta value of MouseState is invalid when the browser send the mouse event to Unity

- com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs
`PeerConnection.Dispose` method is public and call from outside. 
However, the `Dispose` method doesn't suppress the finalizer, so the finalizer is called from garbage collector and cause disposing twice.
> fix: PeerConnection.Dispose method is called twice when unloading the scene

- com.unity.renderstreaming/Samples~/Example/Gyro/GyroSample.cs
`InputControl` of Input sensor device is not reset even if calling `InputSystem.DisableDevice`. Therefore it causes unexpected behavior after unloading the Gyro sample scene.
> fix: Reset InputControl when unloading Gyro sample scene

- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
- add check null conditional operator when `Stop`
> fix: Null reference exception when close websocket

- com.unity.renderstreaming/Runtime/Scripts/MicrophoneStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
- Cut off microphone feedback on `OnAudioFilterRead`
- not use `WebRTC.AudioCustomFilter` because `SetData` is called by `MicrophoneStreamSender`
> fix: cutoff own microphone feedback

- WebApp/client/public/bidirectional/css/style.css
- WebApp/client/public/bidirectional/index.html
- WebApp/client/public/bidirectional/js/main.js
- WebApp/client/public/bidirectional/js/sendvideo.js
- WebApp/client/public/css/main.css
- WebApp/client/public/js/peer.js
- WebApp/client/public/multiplay/index.html
- WebApp/client/public/multiplay/js/main.js
- WebApp/client/public/multiplay/js/video-player.js
- WebApp/client/public/receiver/css/style.css
- WebApp/client/public/receiver/index.html
- WebApp/client/public/receiver/js/main.js
- WebApp/client/public/receiver/js/receiver.js
- WebApp/client/test/peerconnection.test.js
- WebApp/client/test/peerconnectionmock.js
- WebApp/src/index.ts
- WebApp/src/websocket.ts
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
- Add codec select option each sample on WebApp.
- Add message div for error message or stats about using codec  etc.
- Show error message if failed `onGotDescription` process.
example Receiver sample on got error.
> feat: Select video codec on WebApp

- WebApp/client/public/js/sender.js
Because 'resize' event is not working for div, we can use 'ResizeObserver' to monitor div dimension changes.
> fix: Correct resize mapping bug

- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
This pull request fixes the blocking the main thread when using the method of `HttpSignaling` class. `HttpSignaling` class uses `HttpWebRequest` internally to make HTTP request for web server. however, `HttpWebRequest.GetResponse` is not executed asyncnously, so it blocks the main thread.
> fix: Execute http request on worker thread

- com.unity.renderstreaming/Editor/RenderStreamingEditor.cs
Cache `ISignaling` derieved types, so there is no scanning over all assemblies on each inspector tick.
Resolves #717
> fix: `RenderStreamingEditor` performance

- com.unity.renderstreaming/Runtime/Scripts/AvailableCodecsUtils.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamSenderBase.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingEventProviderTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
This pull request changes the timing of the WebRTC initialization process. This makes available to call WebRTC APIs anytime in the Unity Render Streaming package.
To call WebRTC APIs, `WebRTC.Initialize` must be called once at first.
For example, since we need to define static methods to get available codec list, this pull request added the initialization process using Unity attributes `InitializeOnLoadAttribute` and `RuntimeInitializeOnLoadMethodAttribute`. This can complete the initialization process before calling static methods.
> fix: Call once WebRTC.Initialize when the Unity Editor is launched

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/Broadcast.cs
- com.unity.renderstreaming/Runtime/Scripts/IRenderStreamingHandler.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingEventData.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingEventProvider.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Runtime/Scripts/SingleConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamReceiverBase.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamSenderBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingEventProviderTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
We define multiple components to stream video/audio.
- `VideoStreamSender`
- `VideoStreamReceiver`
- `VideoStreamSender`
- `AudioStreamReceiver`
These components should own RTCRtpTransceiver instance to control stream more detail. Since this pull request refactor code to take the instance to these components.
> refactor: Stream class owns RTCRtpTransceiver instance to configure stream codec

- .gitignore
- com.unity.renderstreaming/Runtime/Scripts/AudioCodecInfo.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioCodecInfo.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderTextureBlitter.cs
- com.unity.renderstreaming/Runtime/Scripts/ScreenStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamReceiverBase.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamSenderBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoCodecInfo.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoCodecInfo.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/WebCamStreamSender.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
This PR adds the static method to get available video/audio codecs on the system. 
Added two classes which express the audio/video codec to get codec properties.
- `VideoCodecInfo`
- `AudioCodecInfo`
In addition, defined inherited classes to express specific codec properties like H264 and VP9.
- `H264CodecInfo`
- `VP9CodecInfo`
> feat: Add VideoCodecInfo / AudioCodecInfo

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
In WebRTC API, we can set the range of bitrate for video/audio streaming. Therefore, this pull request changes the arguments of methods `VideoStreamSender.SetBitrate` and `AudioStreamSender.SetBitrate`.
> fix: Change argument of SetBitrate to set value as range

- com.unity.renderstreaming/Runtime/Scripts/VideoCodecInfo.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
The `GetAvailableCodec` method on some environments like Android platform may return VP9 codec which not contains profile information. This change makes the type of `VP9CodecInfo.profile` property optional.
> fix: The profile property of VP9CodecInfo is optional

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
Setting parameters on the Audio or Video sender is resulting in "null" error messages in the debug log.
This is due to the error logging only occuring when there isn't an error.
With this commit it should now only log when set calls are unsuccessful.
To replicate, call a set method during runtime.
The console, or debug log, will contain errors that say null when the set is successful.
> fix: fix logging errors on success

- com.unity.renderstreaming/Editor/PropertyDrawers/FrameRateDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/FrameRateDrawer.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
Added the property drawer for the frame rate of the video streaming.
> fix: Add FrameRatePropertyDrawer 

- BuildScripts~/template/remote.sh.template
- BuildScripts~/test_package_mac.sh
- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/739
This comment in this code describes about the workaround.
```
/// todo(kazuki):: This is workaround.
/// When kicking the Unity Editor with batchmode flag on command line, The Unity Editor crashes 
/// caused by not unloading WebRTC native plugin. By this workaround, Some static methods of this
/// package don't work correctly when batchmode. These static methods depend on WebRTC API,
/// therefore the package initialization must be completed just after launching Editor.
/// In the future, we will remove this workaround after improving the initialization of the
/// WebRTC package.
> fix: [workaround] Avoid crash when build app with batchmode on command-line

- com.unity.renderstreaming/Editor/PropertyDrawers/BitrateDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/BitrateDrawer.cs.meta
- com.unity.renderstreaming/Editor/PropertyDrawers/FrameRateDrawer.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
Add the new PropertyDrawer which available to set range of bitrate.
Also, **BitrateAttribute** class can sets min/max of the slider.
```csharp
[SerializeField, Bitrate(0, 10000)]
private Range m_bitrate = new Range(s_defaultMinBitrate, s_defaultMaxBitrate);
```
> feat: Add BitrateDrawer 

- com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Tests/Runtime/InputSystem/InputRemotingTest.cs
- com.unity.renderstreaming/Tests/Runtime/PeerConnectionTest.cs
- com.unity.renderstreaming/Tests/Runtime/PeerConnectionTest.cs.meta
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
Delegate `SetDescription` process to `Unity.RenderStreaming.PeerConnection` class.
Changed to `SetDescription` processing is not executed in parallel.
Add test about `Unity.RenderStreaming.PeerConnection` class.
- Confirm that the result is according to the current `SignalingState`.
- Check the behavior when receiving description while processing other description.
```
PeerConnectionTest
- SendOfferTwiceImmediately
- SendAnswerTwiceImmediately
- OnGotOfferDescriptionAfterSendOfferImmediatelyInPolite
- OnGotOfferDescriptionAfterSendOfferImmediatelyInImPolite
- OnGotAnswerDescriptionAfterSendOfferImmediately(polite/impolite)
- OnGotOfferDescriptionAfterSendAnswerImmediately(polite/impolite)
```
> feat: Delegate SetDescription process to PeerConnection class

- com.unity.renderstreaming/Editor/PropertyDrawers/BitrateDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/CodecDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/CodecDrawer.cs.meta
- com.unity.renderstreaming/Editor/SerializedPropertyExtension.cs
- com.unity.renderstreaming/Editor/SerializedPropertyExtension.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/AudioCodecInfo.cs
- com.unity.renderstreaming/Runtime/Scripts/Codec.cs
- com.unity.renderstreaming/Runtime/Scripts/Codec.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/VideoCodecInfo.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/SceneSelectUI.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
This pull request adds the dropdown UI to select video codec on the inspector window.
If the codec contains multiple options like H264, you can choise them.
It also defined a serializable data to represent codec information.
```csharp
internal struct Codec<T> : IEquatable<RTCRtpCodecCapability>
{
public string codecName;
public string sdpFmtpLine;
}
```
> feat: Add CodecDrawer

- com.unity.renderstreaming/Editor/VideoStreamReceiverEditor.cs
- com.unity.renderstreaming/Editor/VideoStreamReceiverEditor.cs.meta
- com.unity.renderstreaming/Editor/VideoStreamSenderEditor.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/Broadcast.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Runtime/Scripts/SingleConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamReceiverBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/ARFoundation/ARFoundation.unity
- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
- com.unity.renderstreaming/Samples~/Example/Broadcast/Broadcast.unity
- com.unity.renderstreaming/Samples~/Example/Gyro/Gyro.unity
- com.unity.renderstreaming/Samples~/Example/Multiplay/Guest.prefab
- com.unity.renderstreaming/Samples~/Example/Multiplay/Player.prefab
- com.unity.renderstreaming/Samples~/Example/Receiver/Receiver.unity
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/HDRP.unity
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/URP.unity
- com.unity.renderstreaming/Samples~/Example/WebBrowserInput/WebBrowserInput.unity
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
This pull request adds the custom component of `VideoStreamReceiver`.
There are two options for receiving video streaming.
- Render Texture
- API Only
If you select **Render Texture** option, receiving texture will be copyed to Render Texture attaching the component. 
**API Only** is for fetching received texture with script instead of texture copy.
> feat: Add VideoStreamReceiverEditor

- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
This pull request avoids the exception in Broadcast sample.
`VideoStreamSender` class throw **InvalidOperationException** during calling the `SetTextureSize` method when VideoStreamSource.Texture as the VideoStreamSender.source property.
> fix: Avoid exception when using VideoStreamSource.Texture as  in the Broadcast sample

- .yamato/meta/environments.yml
- .yamato/upm-ci-renderstreaming-packages.yml
This PR revert the previous PR #603.
Additionally, Removed Unity2019.4 from the supporting Unity version list.
> chore: Add Unity2021.3 to the list of test environment when publishing the package

- com.unity.renderstreaming/Samples~/Example/Broadcast/Broadcast.unity
Screen don't display UI in broadcast sample because of the `Video Stream Source` option of the `VideoStreamSender` component.
We can fix it by changing the option to *Screen* instead of *Camera*.
> fix: Fix VideoSteramSource in Broadcast sample

- com.unity.renderstreaming/Samples~/Example/WebBrowserInput/WebBrowserInput.unity
When setting *AudioListener* as the Audio Source option in `AudioStreamSender` component, we need to attrach `AudioListener` component to the GameObject which attaching `AudioStreamSender`.
We should fix this behaviour but `AudioStreamTrack` class in WebRTC package must support the constructor which has argument for `AudioListener`.
> fix: Fix InvalidOperationException in WebBrowserInput sample

- WebApp/src/class/httphandler.ts
- WebApp/test/httphandler.test.ts
Fix disconnection can't get when session2 disconnects before session1 answer. e42306352aa4485b97626ed7af1934e2075b739a
And add test about this case.
> Fix: deadconnection handle httpsingaling

- com.unity.renderstreaming/Editor/PropertyDrawers/CodecDrawer.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioCodecInfo.cs
- com.unity.renderstreaming/Runtime/Scripts/Codec.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoCodecInfo.cs
- com.unity.renderstreaming/Tests/Editor/AudioCodecInfoObject.cs
- com.unity.renderstreaming/Tests/Editor/AudioCodecInfoObject.cs.meta
- com.unity.renderstreaming/Tests/Editor/EditorTest.cs
- com.unity.renderstreaming/Tests/Editor/Unity.RenderStreaming.EditorTests.asmdef
- com.unity.renderstreaming/Tests/Editor/VideoCodecInfoObject.cs
- com.unity.renderstreaming/Tests/Editor/VideoCodecInfoObject.cs.meta
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
Fix a bug about serializing VideoCodecInfo/AudioCodecInfo.
To test this fix, added the two unit-tests.
-  EditorTest.SerializeVideoCodecInfo
-  EditorTest.SerializeAudioCodecInfo
> fix: Fix a bug about serializing VideoCodecInfo/AudioCodecInfo

- com.unity.renderstreaming/Samples~/Example/Receiver/ReceiverSample.cs
If `renderStreaming.runOnAwake` checked, this sample occurred `NullReferenceException` when `OnUpdateReceiveTexture` invoked.
> fix: Fix NullReferenceException on receiver sample

- com.unity.renderstreaming/Samples~/Example/ARFoundation/ARFoundationSample.cs
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Samples~/Example/Gyro/GyroSample.cs
- com.unity.renderstreaming/Samples~/Example/Multiplay/Multiplay.cs
- com.unity.renderstreaming/Samples~/Example/Multiplay/MultiplaySample.cs
- com.unity.renderstreaming/Samples~/Example/Receiver/ReceiverSample.cs
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/RenderPipelineSample.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/SampleManager.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/SampleManager.cs.meta
- com.unity.renderstreaming/Samples~/Example/Scripts/SceneSelectUI.cs
- com.unity.renderstreaming/Samples~/Example/WebBrowserInput/WebBrowserInputSample.cs
This PR fixes sample scenes works well independently without menu scene.
Before that, sample scenes depended on initializing the menu scene. `SceneManager` class manages global settings for sample scenes and fixes that samples will work even if the manager is not initialized.
> fix: Add SampleManager to manage global settings for sample

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamSenderBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
Related issue.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/663
This pull request fixes the issue that not releasing the webcam device handle after destroying the scene. This issue caused by not calling `Dispose` method of `VideoStreamSourceImpl` instance, so this fix added `OnDestroy` method and call `Dispose`.
Additionally, this change fixes another issue. `WebCamTexture` constructor returns texture instance, however, its size is very small sometimes. It fixes by the waiting process of `WebCamTexture.didUpdateThisFrame` to wait timing for the suitable texture.
> fix: Fix the process of destroying WebCamTexture in VideoStreamSender

- com.unity.renderstreaming/Runtime/Scripts/VideoCodecInfo.cs
Fix the name of H264Profile enum `ProfileMain` to `Main` .
> fix: Fix enum name of H.264 profile

- com.unity.renderstreaming/Editor/PropertyDrawers/CodecDrawer.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioCodecInfo.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
This PR fixes the issue that the audio codec option doesn't effect the actual codec in play mode.
The audio codec option in *AudioStreamSender* component and *AudioStreamReceiver* component.
Audio codec options have properties **channelCount** and **sampleRate** unlike video codec options.
> fix: Fix audio codec selector in Unity Editor

- WebApp/client/public/receiver/js/main.js
Fixed the javascript error below.
```
Uncaught (in promise) TypeError: renderstreaming is undefined <anonymous> http://127.0.0.1/receiver/js/main.js:35 EventListener.handleEvent* http://127.0.0.1/receiver/js/main.js:34
```
> fix: Fix TypeError when reloading the web page of the Receiver sample 

- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- Set up test project with RenderStreaming samples
- Run broadcast sample
- Connect to receiver example in chrome browser
- Once connection is established hit F5 to refresh the page, (or can force quit chrome app)
- If you add logging the Unity application will indefinitely send offers for the previous established PeerConnection
Expected behavior:
- Eventually PeerConnections that were improperly closed will be destroyed
How this was tested:
- Tested the above steps with logging to track that PeerConnections are cleaned up once they transition into the failed state
- Ran unit tests locally to confirm they are passing
> Fix offers being resent indeffinitely when PeerConnection is in failed state

- .yamato/compile-package.yml
- .yamato/package.metafile
- .yamato/upm-ci-renderstreaming-packages.yml
- .yamato/upm-ci-template.yml
- RenderStreaming~/Packages/packages-lock.json
- com.unity.renderstreaming/Runtime/Unity.RenderStreaming.Runtime.asmdef
- com.unity.renderstreaming/package.json
Original PR is here. Thanks for @mihai-unity
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/796
The Unity Render Streaming package may contains the bug which makes the timeout when quitting the Unity Editor. We add the CI job to detect the issue more easily.
> ci: Add CI jobs which is package isolation test for detecting issues

- WebApp/src/class/httphandler.ts
- WebApp/test/httphandler.test.ts
- Set up test project with RenderStreaming samples
- Run broadcast sample
- Connect to receiver example in chrome browser
- Once connection is established hit F5 to refresh the page, (or can force quit chrome app)
- If you check the webserver app, you will see that no "deleted" message is logged even after the 10 second timeout
Expected behavior:
- Timed out sessions will be deleted after the 10 second time out
How this was tested:
- Added a new test that failed to replicate the issue
- Ran tests after fix was implemented to confirm it fixed issue
- Tested the above steps with the package samples to confirm orphaned connections are cleaned up
Log from webserver demonstrating timeout clean-up of improperly disconnected session:
> fix: fix sessions lingering after they were timed out

- com.unity.renderstreaming/Editor/PropertyDrawers/CodecDrawer.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoCodecInfo.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/SceneSelectUI.cs
The internal video codec factory in libwebrtc implements two profiles of AV1 video codec, *Profile 0* and *Profile 1*. Add a note, this option is for only receiver side, not sender.
This pull request provides dropdown UI on Inspector Window to choice these options.
> fix: Fix option title of av1 video codec on inspector window

- com.unity.renderstreaming/Samples~/Example/ARFoundation/ARFoundationSample.cs
In latest example code, there is a bug on ARFoundationSample.cs.
it is not a critical bug, however I think it should be fixed.
BRs.
> [Bugfix] fix AFoundationSample when script is disabled.

- com.unity.renderstreaming/Runtime/Scripts/InputReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputManager.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputRemoting.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
When using Android device, we got assersion from Input System package below.
```
Could not find active control after binding resolution
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Assert(Boolean, String)
UnityEngine.InputSystem.InputActionState:RestoreActionStatesAfterReResolvingBindings(UnmanagedMemory, InputControlList`1, Boolean)
UnityEngine.InputSystem.InputActionState:FinishBindingResolution(Boolean, UnmanagedMemory, InputControlList`1, Boolean)
UnityEngine.InputSystem.InputActionMap:ResolveBindings()
UnityEngine.InputSystem.InputActionMap:LazyResolveBindings(Boolean)
UnityEngine.InputSystem.InputActionState:OnDeviceChange(InputDevice, InputDeviceChange) …
```
> fix: Avoid assertion from Input System package when using Android device

- WebApp/client/public/bidirectional/index.html
- WebApp/client/public/bidirectional/js/main.js
- WebApp/client/public/multiplay/index.html
- WebApp/client/public/multiplay/js/main.js
- WebApp/client/public/receiver/index.html
- WebApp/client/src/peer.js
- WebApp/client/src/renderstreaming.js
HTML attribute `disabled` behaves differently on firefox and others.
1. Open "Bidirectional" page.
2. You can see the "Set Up" button is disabled at first.
3. Push "Start Video" button, and "Set Up" button is changed to enabled.
4. Refreah the web page, the "Set Up" buton should be returned to disabled.
https://user-images.githubusercontent.com/1132081/211533091-35cedcd5-1cb8-40d5-a5b8-05df8527a291.mp4
https://user-images.githubusercontent.com/1132081/211533061-792fba05-d75d-4a3a-bee4-173dbf40e105.mp4
Surprisingly, this issue has been reported since 12 years ago.
https://bugzilla.mozilla.org/show_bug.cgi?id=654072
We can avoid this issue with `autocomplete="off"`. That's insane.
> fix: Add autocomplete attribute into input elements to avoid issue of "disabled" attribute on Firefox

- WebApp/client/test/signaling.test.js
- WebApp/src/class/options.ts
- WebApp/src/index.ts
- WebApp/src/server.ts
- com.unity.renderstreaming/CHANGELOG.md
- com.unity.renderstreaming/Documentation~/launch-webapp.md
- com.unity.renderstreaming/Documentation~/signaling-type.md
- com.unity.renderstreaming/Documentation~/webapp.md
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
We provided the signaling server which use HTTP polling as a signaling messaging protocol in default. This PR changes websocket the default messaging protocol. Comparing the response of messaging, websocket is faster than HTTP polling.
And the command line option is changed. `-type` or `-type` option is added in this PR. You can make command below If you want to change the type of signaling protocol to HTTP polling, 
```
webserver.exe -t http
```
```
webserver.exe -type http
```
> fix: websocket is in default as a signaling protocol

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamSenderBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/Broadcast.unity
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
This PR fixes VideoStreamSender and AudioStreamSender to make available changing properties of media source while streaming.
Additionally, added dropdown UI to test the feature in Broadcast sample.
https://user-images.githubusercontent.com/1132081/213084830-6644bf5b-5ed2-4547-b072-ccf7350b02ae.mov
> fix: Make available to change properties of VideoStreamsender and AudioStreamSender while streaming

- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingHandler.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingSettings.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/SceneSelectUI.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
This PR defines `IceServer` class which manages STUN/TURN configuraiton. Before that, Inspector window is a only place to change configuration of ICE server. We can make new APIs for managing ICE server with this class.
> feat: Define IceServer class to control signaling settings with APIs

- com.unity.renderstreaming/Editor/PropertyDrawers/SignalingSettingsDrawer.cs
- com.unity.renderstreaming/Editor/RenderStreamingProjectSettingsProvider.cs
- com.unity.renderstreaming/Editor/SignalingManagerEditor.cs
- com.unity.renderstreaming/Runtime/Scripts/AutomaticStreaming.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/SignalingSettingsObject.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingManager.cs
- com.unity.renderstreaming/Runtime/SignalingSettings.asset
- com.unity.renderstreaming/Runtime/SignalingSettings.asset.meta
- com.unity.renderstreaming/Samples~/Example/ARFoundation/ARFoundationSample.cs
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Samples~/Example/Gyro/GyroSample.cs
- com.unity.renderstreaming/Samples~/Example/Menu/Menu.unity
- com.unity.renderstreaming/Samples~/Example/Multiplay/MultiplaySample.cs
- com.unity.renderstreaming/Samples~/Example/Receiver/ReceiverSample.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/SceneSelectUI.cs
- com.unity.renderstreaming/Samples~/Example/WebBrowserInput/WebBrowserInputSample.cs
- com.unity.renderstreaming/Tests/Editor/EditorTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingManagerTest.cs
This pull request makes ScriptableObject for SignalingSettings class and can set settings into SignalingManager inspector. Signaling settings is also configured in Project Settings window, developers select the reference of settings from two ways, from Project Settings or SignalingManager inspector.
https://user-images.githubusercontent.com/1132081/216274700-7803e551-3fb4-490c-9857-ffb6642fa334.mov
> feat: Define SignalingSettings asset to make portable signaling configurations

- com.unity.renderstreaming/Editor/RenderStreamingSettings.asset
- com.unity.renderstreaming/Editor/RenderStreamingSettings.asset.meta
- com.unity.renderstreaming/Editor/SignalingManagerEditor.cs
- com.unity.renderstreaming/Runtime/Scripts/CommandLineParser.cs
- com.unity.renderstreaming/Runtime/Scripts/CommandLineParser.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/Signaling/FurioosSignalingSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignalingSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/SignalingSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignalingSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingManager.cs
- com.unity.renderstreaming/Tests/Editor/EditorTest.cs
- com.unity.renderstreaming/Tests/Runtime/CommandLineParserTest.cs
- com.unity.renderstreaming/Tests/Runtime/CommandLineParserTest.cs.meta
- com.unity.renderstreaming/Tests/Runtime/InputSystem/InputEditorUserSettingsTest.cs
- com.unity.renderstreaming/Tests/Runtime/PeerConnectionTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingTest.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignalingSettings.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingManagerTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingSettingsTest.cs
This pull request adds commandline arguments support. Please see details below.
| arguments | description |
| --- | --- |
| `signalingType <value>` | Class type of the signaling. `http` or `websocket`. |
|  `signalingUrl  <value>` | Set the signaling server URL. If you use WebSocket as a signaling protocol, you should specify a URL starting with `ws` or `wss`. |
| `iceServerUrl <value>` | Set URLs of STUN/TURN servers.  |
| `iceServerUsername <value>` | The username to use when logging into the TURN server. |
| `iceServerCredential <value>` | The credential to use when logging into the TURN server. |
| `iceServerCredentialType <value>` | This attribute specifies what kind of credential is to be used when connecting to the TURN server. |
| `pollingInterval  <value>` | Http polling interval …
> feat: Add command line option for stanadlone app

- com.unity.renderstreaming/Tests/Runtime/SignalingManagerTest.cs
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/529
This issue not reproduced on current version.
By changing the test, it does not reproduce.
> fix: Signaling Manager test Run again immediately. 

- com.unity.renderstreaming/Samples~/Example/Broadcast/CameraControl.inputactions
This PR fixes the issue related https://github.com/Unity-Technologies/UnityRenderStreaming/issues/454.
> fix: Fix primary touch position on iPad

- com.unity.renderstreaming/Editor/RenderStreamingWizard.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
User reported Question1 on https://github.com/Unity-Technologies/UnityRenderStreaming/issues/868
I reproduce on main branch.
Changes from scripts in Scriptable Objects will not be persisted at the end Editor unless `SetDirty`.
> Fix: fix update input settings by wizard

- com.unity.renderstreaming/Editor/WebAppDownloader.cs
Change release branch name to full version name instead of only version number.
> Fix: fix get URL about Web App source code

- RenderStreaming~/ProjectSettings/EditorBuildSettings.asset
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/HDRP.unity
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/URP.unity
Build error on Unity 2020.3.
Asset version serialized in HDRP/URP scene is not supported in 2020.3
> Fix: fix the version of Serialized Reference Object by URP/HDRP scene

- com.unity.renderstreaming/Editor/ConfigInfoLine.cs
- com.unity.renderstreaming/Editor/RenderStreamingWizard.cs
InputSettings that do not exist under Assets can't modify, so added check and fix button that create asset under Assets Folder.
> Fix: Create input settings from wizard

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
We got an error when using `AudioSourceType.Microphone` in Broadcast sample. The cause of this error is attaching multiple AudioSource components to the single gameObject. To fix this issue, this pull request fixes that instantiate new GameObject for attaching AudioSource component to play Microphone.
```
GameObject has multiple AudioSources and/or AudioListeners attached. While built-in filters like lowpass are instantiated separately, components implementing OnAudioFilterRead may only be used by either one AudioSource or AudioListener at a time.
The reason for this is that any state information used by the callback exists only once in the component, and the source or listener calling it cannot be inferred from the callback.
In this case the OnAudioFilterRead callback of script …
```
> fix: Fix issue when using AudioSourceType.Microphone

- com.unity.renderstreaming/Editor/VideoStreamSenderEditor.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
This PR fixes this issue. https://github.com/Unity-Technologies/UnityRenderStreaming/issues/859
> fix: Fix SetTextureSize when using VideoSourceType.Texture

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/AutomaticStreaming.cs
The Track used for `SetData` and the Track used for stream are different.
> Fix: Stream AudioStreamTrack APIOnly

- WebApp/src/class/httphandler.ts
- WebApp/test/httphandler.test.ts
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
- Set up test project with RenderStreaming samples
- Run webapp sample
- Run broadcast sample
- Connect to receiver example in chrome browser
- Once connection is established hit back in Unity application
- Log will not print out polling thread ended, and the webapp logs won't indicate a disconnect has occured.
- Doing this over and over will result in the signaling server having a large collection of timed out sessions, and can interfer with client connections.
Description of the changes:
- Allow HttpSignaling thread to exit gracefully on Stop(), by joining with a time out of interval * 2 to account for the polling interval & time to send a disconnect message. 
- Swap HttpSignaling thread to a [background thread](https://learn.microsoft.com/en-us/dotnet/standard/threadin …
> fix: Fix timed out sessions collecting in signaling server

- WebApp/client/src/pointercorrect.js
- WebApp/client/src/sender.js
- WebApp/client/test/domvideoelement.js
- WebApp/client/test/pointercorrect.test.js
This is a PR to fix incorrect pointer coordinates computation using the sample client WebApp.
Previously the video player element would trigger a call to the _onResize() function "recomputing" its position and size when resized. The issue that can arise is that if the video player move without resizing (which is what happening on my side because I move it around in my web page) then its position is not updated and thus the mapping of the mouse coordinates is not working as expected.
The fix is simple: Instead of storing the video player rectangle (position and size) we instead keep a reference to it and compute its rectangle each time we need it in the pointer mapping function.
> Recompute video player position each time

- WebApp/client/src/signaling.js
- WebApp/client/test/mocksignaling.js
- WebApp/client/test/signaling.test.js
- WebApp/package-lock.json
- WebApp/src/class/httphandler.ts
- WebApp/test/httphandler.test.ts
- WebApp/test/renderstreaming.postman_collection.json
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/SignalingMessage.cs
The resolution in the `Date` header is 1 second. Therefore, if the polling interval is 1 second or less, the `fromtime` of QueryParameter may become the same, and unnecessary responses may be received.
Include the exact last used Timestamp in the `GetAll` response and use it to support short polling intervals.
> fix: Error on http signaling using short interval 

- WebApp/client/public/css/main.css
- WebApp/client/public/index.html
- WebApp/client/public/js/config.js
- WebApp/client/public/js/icesettings.js
- WebApp/client/public/js/main.js
- com.unity.renderstreaming/Runtime/Scripts/Signaling/SignalingSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingManager.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/SceneSelectUI.cs
This PR fixes this issue.
- https://github.com/Unity-Technologies/UnityRenderStreaming/issues/907
- https://github.com/Unity-Technologies/UnityRenderStreaming/issues/895
To make changing ICE configration easy on web client, added the web UI to configure ICE server list.
> fix: Fix thte issue that ICE server configuration are not changed 

- com.unity.renderstreaming/Runtime/Scripts/Broadcast.cs
- com.unity.renderstreaming/Runtime/Scripts/DataChannelBase.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Samples~/Example/WebBrowserInput/WebBrowserInputChannelReceiver/WebBrowserInputChannelReceiver.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
- Set up test project with RenderStreaming samples.
- Run webapp sample.
- Run WebBrowserInput sample.
- Connect in browser, and open VideoPlayer sample.
- Connect again in browser, and open VideoPlayer sample.
- Close the first tab.
- The still open tab will no longer receive mouse or keyboard input.
Description of the changes:
- Update Broadcast.cs to only disconnect datachannels that are associated with the disconnected connectionId. 
- Update WebBrowserInputChannelReceiver.cs to disconnect from the RTCDataChannel when disconnecting to prevent processing input events when disconnecting.
How this was tested:
- Tested by running RenderStreaming unit tests & adding a new test to cover this issue.
- Ran through package samples, and the above reproduction steps.
> fix: DataChannel closing all connections

- com.unity.renderstreaming/Runtime/Scripts/SignalingManager.cs
This fix is issued from these comments.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/907#issuecomment-1657696511
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/502#issuecomment-1526610985
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/895#issuecomment-1654854938
**OfType<T>** method in Linq returns empty array even if defining type cast method.
> fix: Ice servers settings doesn't affecte when runOnAwake is enabled

- com.unity.renderstreaming/Editor/SignalingManagerEditor.cs
When disabling the flag "Use Default Settings in Project Settings", throws an exception below.
```
NullReferenceException: SerializedObject of SerializedProperty has been Disposed.
UnityEditor.SerializedProperty.get_objectReferenceValue () (at /home/bokken/build/output/unity/unity/Editor/Mono/SerializedProperty.bindings.cs:1232)
Unity.RenderStreaming.Editor.SignalingManagerEditor.OnProjectChanged () (at ./Library/PackageCache/com.unity.renderstreaming@4e408551e619/Editor/SignalingManagerEditor.cs:159)
UnityEditor.EditorApplication.Internal_CallProjectHasChanged () (at /home/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:409)
UnityEditor.AssetDatabase:CopyAsset(String, String)
Unity.RenderStreaming.Editor.SignalingManagerEditor:CreateDefaultSignalingSettings() (at …
```
> fix: Fix NullReferenceException when disabling a flag on SignalingManager inspector

- com.unity.renderstreaming/Runtime/Scripts/CommandLineParser.cs
- com.unity.renderstreaming/Tests/Runtime/CommandLineParserTest.cs
- Create HttpSignalingSettings with providing iceServers.
- Call ParseArguments on the HttpSignalingSettings without any IceServerUrl parameters defined.
- The first iceServer will have it's urls replaced with nulls.
- For an application, this could be replicated by running the application with command line arguments that weren't related. In my case, running an application with -force-vulkan would cause it to replace the iceServerUrls.
Description of the changes:
- The commandline parser was returning an empty list when parsing the URL parameters when none were provided on the command line. As a result, the HttpSignalingSettings class would replace the URLs with empty ones since it thought the values were set. This would then later cause issues when connecting since the …
> Fix command line arguments incorrectly replacing ice-candidates with null values leading to a crash

- com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingManagerInternal.cs
- Establish a WebRTC connection between peers.
- Simulate an internet drop / prevent traffic from reaching the ice candidate for 5 seconds.
- Re-establish connection between the peers.
- The PeerConnection will now be disconnected, and the signaling server will not be informed unless it also was unreachable, and timed out itself. 
Description of the changes:
- The disconnected state can happen when the connection between peers is tested and fails a single time. A disconnected state can happen from packet loss, or during shortlived network disruptions. Failed happens after failing to reach the peer 5 times in a row, and represents that the connection is likely no longer valid. This change swaps to disconnecting the peers on failed instead of disconnect, as less reliable …
> Fix disconnecting on first time PeerConnection state changes to disconnected, and instead rely on failed.
