- WebApp/package-lock.json
Called this command to reduce duplication npm dependencies.
```
npm dedupe
```
https://docs.npmjs.com/cli/dedupe.html
> fix: Reduce duplication npm dependencies

- Packages/com.unity.template.renderstreaming/Documentation~/index.md
- Packages/com.unity.template.renderstreaming/Documentation~/jp/index.md
- Add the limitation for Graphics API
- Add the limitation for Scripting Backend
> doc: fixed requirements

- Packages/com.unity.template.renderstreaming/Documentation~/en/https.md
found some small typos in Documentation~/en/https.md
> fixes typos in https.md

- WebApp/.eslintrc.js
- WebApp/package-lock.json
- WebApp/package.json
- WebApp/src/index.ts
- WebApp/src/log.ts
- WebApp/src/server.ts
- WebApp/src/signaling.ts
- WebApp/tslint.json
tslint will deprecate in 2019
https://github.com/palantir/tslint/issues/4534
> Migrate from tslint to eslint

- .yamato/unity-translate.yml
We create Unity Translate projects for localizing unity packages
> ci: add unity-translate workflow

- Assets/Scripts/Editor/RenderStreamingEditor.cs
- Assets/Scripts/RenderStreaming.cs
This PR hasn't passed auto-testing.
Reverts Unity-Technologies/UnityRenderStreaming#182
Please check this error
```
Assets/Scripts/RenderStreaming.cs(113,17): error CS0246: The type or namespace name 'JsonICE' could not be found (are you missing a using directive or an assembly reference?)
```
> Revert "add standalone player command line args for ICE JSON url and signaling"

- WebApp/package-lock.json
- WebApp/package.json
As we got an alert from a npm audit security report, 
`npm audit fix` command I executed and fix the issue.
> fix: npm security alert

- Packages/com.unity.renderstreaming/Editor/RenderStreamingMenu.cs
Try downloading webserver from a known version if the webserver of the current version doesn't exist.
> fix: webserver download backup

- Assets/Scenes/samplescene.unity
- Assets/Scripts/RemoteInput.cs
- Assets/Scripts/RenderStreaming.cs
- Assets/Scripts/UIController.cs
Issue: https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-3#post-5214983
> fix: display the mouse pointer in the correct position 

- CONTRIBUTING.md
- LICENSE.md
We should put two files to root folder 
- LICENSE.md
- CONTRIBUTING.md
> doc: Add LICNSE.md and CONTRIBUTING.md to root

- Assets/Scripts/RenderStreaming.cs
just pass the depth format in CaptureStream as a sample
> feat: Pass depth format in CaptureStream

- .yamato/promotion.yml
- .yamato/upm-ci-renderstreaming-packages.yml
- .yamato/upm-ci-renderstreaming-unitypackage.yml
- .yamato/upm-ci-template.yml
- EmptyProjectForTest~/Packages/manifest.json
- Packages/com.unity.renderstreaming/package.json
- Packages/com.unity.template.renderstreaming/package.json
- Packages/manifest.json
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Packages/manifest.json
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Packages/manifest.json
Upgrade `com.unity.webrtc` version `1.1.0`
> chore: update package.json

- .yamato/meta/environments.yml
- .yamato/upm-ci-publish-github-release.yml
- .yamato/upm-ci-template.yml
- Assets/Tests.meta
- Assets/Tests/Runtime.meta
- Assets/Tests/Runtime/RenderStreamingTest.cs
- Assets/Tests/Runtime/RenderStreamingTest.cs.meta
- Assets/Tests/Runtime/Unity.Template.RenderStreaming.RuntimeTests.asmdef
- Assets/Tests/Runtime/Unity.Template.RenderStreaming.RuntimeTests.asmdef.meta
This PR is for adding jobs to test template package.
- `upm-ci` 1.5.0 is not support template test with option `platform=standalone`
-  `HDRP` 7.1.8 has bug so template test is failed.
> chore: template test

- WebApp/package-lock.json
- WebApp/package.json
- WebApp/public/scripts/signaling.js
- WebApp/public/scripts/video-player.js
- WebApp/src/class/answer.ts
- WebApp/src/class/candidate.ts
- WebApp/src/class/offer.ts
- WebApp/src/index.ts
- WebApp/src/signaling.ts
- WebApp/src/websocket.ts
unity client websocket implement using https://github.com/Unity-Technologies/UnityRenderStreaming/pull/209
- Server implementation is not yet done, working in progress.
- Currently, I don't operation check yet.
> Implement websocket signaling (webapp/webclient)

- WebApp/public/scripts/video-player.js
- WebApp/src/index.ts
- WebApp/src/server.ts
Decide Signaling Protocol by Server options
> chore: signaling protocol detection

- EmptyProjectForTest~/Packages/manifest.json
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Packages/manifest.json
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Packages/manifest.json
- com.unity.renderstreaming/package.json
- com.unity.template.renderstreaming-hd/Assets/Scenes/samplescene.unity
- com.unity.template.renderstreaming-hd/Assets/Scripts/Editor/RenderStreamingEditor.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/RenderStreaming.cs
This PR is for fixing build error when building it with the package below
https://github.com/Unity-Technologies/com.unity.webrtc/tree/develop
> fix: fixed error occured when build with webrtc package 2.0.0

- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/HttpSignaling.cs
Enables https to work on sites without SSL certificates
> Fix: https signaling

- WebApp/package.json
- WebApp/tsconfig.json
In this PR fixed lint error below
```
No files matching the pattern "'src/*.ts'" were found.
Please check for typing mistakes in the pattern.
```
> fix: eslint settings

- WebApp/public/scripts/gamepadEvents.js
- com.unity.template.renderstreaming-hd/Assets/Scenes/samplescene.unity
- com.unity.template.renderstreaming-hd/Assets/Scripts/RemoteInput.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/RenderStreaming.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/ISignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/SimpleCameraController.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/UIController.cs
- com.unity.template.renderstreaming-hd/Packages/manifest.json
This pull request is for support multi-controller.
- It can control multiple cameras
- Each camera is attached `SimpleCameraController`
- Render Streaming manages relations between `DataChannel` and `RemoteInput`
- `RemoteInput` contains 4 types of input devices (mouse, keyboard, touchscreen gamepad)
- mouse
- keyboard
- touch screen
- gamepad
> feat: multi controller support

- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Assets/Scenes/SimpleScene.unity
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Assets/TextMesh Pro
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Assets/TextMesh Pro.meta
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Packages/manifest.json
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/ProjectSettings/EditorSettings.asset
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/ProjectSettings/ProjectVersion.txt
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/InputSystem.inputsettings.asset
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/InputSystem.inputsettings.asset.meta
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/Scenes/SampleScene.unity
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/TextMesh Pro
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/TextMesh Pro.meta
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Packages/manifest.json
- RenderStreamingSampleSrc~/RS_URPSampleSrc/ProjectSettings/EditorBuildSettings.asset
- RenderStreamingSampleSrc~/RS_URPSampleSrc/ProjectSettings/ProjectVersion.txt
- Update `manifest.json` and `UnityVersion.txt`
- Add UI and UI Controller for SampleScene each project
- It's same as HDRP template sample scene
> Fix: hdrp and urp sample project

- com.unity.template.renderstreaming-rtx/Assets/Plugins
- com.unity.template.renderstreaming-rtx/Assets/Scenes/samplescene.unity
- update the sample scene to add the second camera
- add a symbolic link for the plugin folder
> fix: dxr template supported multicamera 

- .yamato/upm-ci-publish-github-release.yml
- WebApp/package.json
- com.unity.renderstreaming/Editor/WebAppDownloader.cs
Upload the webapp application on the GitHub Release as the new version `2.0.0`
> chore: upgrade webapp version 2.0.0

- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Assets/Scenes/SimpleScene.unity
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/Scenes/SampleScene.unity
- com.unity.template.renderstreaming-hd/Assets/Scenes/samplescene.unity
- com.unity.template.renderstreaming-hd/Assets/Scripts/Editor/RenderStreamingEditor.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/RenderStreaming.cs
- com.unity.template.renderstreaming-rtx/Assets/Scenes/samplescene.unity
`Capture Camera` property on the `Render Streaming` inspector replaced `VideoStreamer`
> fix: remove unused members

- com.unity.renderstreaming/Documentation~/TableOfContents.md
- com.unity.renderstreaming/Documentation~/en/input.md
- com.unity.renderstreaming/Documentation~/en/tutorial.md
- com.unity.renderstreaming/Documentation~/index.md
- com.unity.renderstreaming/Documentation~/jp/tutorial.md
- fixed broken link
- Update tutorial document
Translate documents under `Documentation~/en` folder to English.
> doc: fixed document

- WebApp/public/scripts/video-player.js
receive message type is different on firefox.
> Fix:firefox stream

- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/FurioosSignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/HttpSignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/WebSocketSignaling.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/SimpleCameraController.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/WebCamStreamer.cs
- com.unity.template.renderstreaming-hd/ProjectSettings/HDRPProjectSettings.asset
- Not initialized variables
- HDRP default settings not specified
> fix: remove warning

- WebApp/public/scripts/video-player.js
This PR changed that 3rd user receives the same stream as a 1st user.
> fix: fix the process of assigning video and stream on web client-side

- .yamato/meta/environments.yml
- .yamato/promotion.yml
- .yamato/upm-ci-renderstreaming-packages.yml
- .yamato/upm-ci-renderstreaming-unitypackage.yml
- .yamato/upm-ci-template.yml
Fixed CI error caused by `upm-ci-utils`.
> chore: Change upm package version

- README.md
- com.unity.renderstreaming/Documentation~/en/webapp.md
- com.unity.renderstreaming/Documentation~/index.md
- com.unity.renderstreaming/Documentation~/jp/index.md
- com.unity.renderstreaming/Documentation~/jp/webapp.md
- com.unity.template.renderstreaming-hd/Packages/com.unity.template.renderstreaming-hd/Documentation~/index.md
- com.unity.template.renderstreaming-hd/Packages/com.unity.template.renderstreaming-hd/Documentation~/jp/index.md
- com.unity.template.renderstreaming-rtx/Packages/com.unity.template.renderstreaming-rtx/Documentation~/index.md
- com.unity.template.renderstreaming-rtx/Packages/com.unity.template.renderstreaming-rtx/Documentation~/jp/index.md
Microfoft -> Microsoft
Chrominium -> Chromium
> doc: Fix typo

- com.unity.template.renderstreaming-hd/Assets/Scripts/Signaling/HttpSignaling.cs
Add ContentLength = 0 to empty PUT request
> Add ContentLength = 0 to empty PUT request [Issue 311]

- com.unity.renderstreaming/Documentation~/index.md
Fixed a missing link in the package document.
> doc: removed unused link

- .yamato/meta/environments.yml
change image to package-ci/mac
> fix: yamato macos image

- com.unity.renderstreaming/Documentation~/input.md
related Issue https://github.com/Unity-Technologies/UnityRenderStreaming/issues/201
> doc: add workaround for using unity ui on background

- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Assets/Scenes/SimpleRenderStreamingHDRP.unity
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Assets/Sounds
- RenderStreamingSampleSrc~/RS_HDRPSampleSrc_1.x/Assets/Sounds.meta
- RenderStreamingSampleSrc~/RS_LegacyRPSampleSrc/Assets/Scenes/SimpleRenderStreamingLegacyRP.unity
- RenderStreamingSampleSrc~/RS_LegacyRPSampleSrc/Assets/Sounds
- RenderStreamingSampleSrc~/RS_LegacyRPSampleSrc/Assets/Sounds.meta
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/Scenes/SimpleRenderStreamingURP.unity
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/Sounds
- RenderStreamingSampleSrc~/RS_URPSampleSrc/Assets/Sounds.meta
In projects for the package sample, the audio button on the browser is not worked.
This PR is for fixing that. Added symbolic links to sample projects to use an audio clip.
> fix: Fix audio button action

- com.unity.template.renderstreaming-hd/Assets/Scenes/ReceiveVideo.unity
- com.unity.template.renderstreaming-hd/Assets/Scripts/ReceiveVideoViewer.cs
- com.unity.template.renderstreaming-hd/Assets/Scripts/RenderStreaming.cs
- com.unity.template.renderstreaming-hd/Packages/manifest.json
- com.unity.template.renderstreaming-hd/Packages/packages-lock.json
- com.unity.template.renderstreaming-rtx/Packages/manifest.json
- com.unity.template.renderstreaming-rtx/Packages/packages-lock.json
- Update template manifest `com.unity.renderstreaming 2.1.1` -> `com.unity.renderstreaming 2.2.0`
- Enable video decoder method on `ReceiveVideoViewer`
> chore: enable videodecoder method

- com.unity.template.renderstreaming-hd/Assets/Scripts/RenderStreaming.cs
this pr is depend on https://github.com/Unity-Technologies/com.unity.webrtc/pull/260.
implementation refer [this page](https://lealog.hateblo.jp/entry/2019/03/12/114529)
> chore: handle track direction

- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
Generally, all of the signaling processes are asynchronous, so `MockSignaling` should behave in the same way. This pull request introduces the `async/await` for treating multithreading.
To simulate delays in the networking process, Added a code `Task.Delay(10);` to each process.
> test: MockSignaling simulate the messaging asynchronously

- com.unity.renderstreaming/Tests/Editor/RequestJobTest.cs
- com.unity.renderstreaming/Tests/Runtime/ConditionalIgnore.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RemoteInputTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderpipelineTest.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingEventProviderTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/TestUtility.cs
`DocFx` is a tool that generates API documents automatically.
In case the access level of class is "public", it becomes a target of documentation, so fixed the access levels of test classes.
> refactor: Fix class access level

- WebApp/public/bidirectional/js/sendvideo.js
- WebApp/public/js/signaling.js
- WebApp/public/videoplayer/js/video-player.js
- WebApp/src/signaling.ts
- WebApp/test/renderstreaming.postman_collection.json
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
fix working with browser-browser, browser-unity
http signaling not working
maybe related this issue https://github.com/Unity-Technologies/UnityRenderStreaming/issues/389
> fix: bidirectional webclient sample

- com.unity.renderstreaming/Documentation~/sample-arfoundation.md
> doc: fix document

- WebApp/package-lock.json
- WebApp/package.json
- WebApp/public/bidirectional/index.html
- WebApp/public/bidirectional/js/main.js
- WebApp/public/bidirectional/js/sendvideo.js
- WebApp/public/css/main.css
- WebApp/public/index.html
- WebApp/public/js/config.js
- WebApp/public/js/main.js
- WebApp/public/videoplayer/index.html
- WebApp/public/videoplayer/js/main.js
- WebApp/public/videoplayer/js/video-player.js
- WebApp/src/class/options.ts
- WebApp/src/index.ts
- WebApp/src/server.ts
- WebApp/test/renderstreaming.postman_collection.json
> feat: display server config on webclient

- com.unity.renderstreaming/Documentation~/sample-receiver.md
> doc: Add docs of Receiver sample

- com.unity.renderstreaming/Samples~/Example/RenderPipeline/HDRP.unity
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/URP.unity
- assign `Input System Channel Receiver` to `SimpleCameraController`.
- remove `Audio` gameobject ( this is no need.)
> Fix: input receiver assignment on renderpipeline scene

- WebApp/public/bidirectional/js/main.js
- WebApp/public/bidirectional/js/sendvideo.js
- WebApp/public/js/gamepadEvents.js
- WebApp/public/js/logger.js
- WebApp/public/js/register-events.js
- WebApp/public/js/signaling.js
- WebApp/public/videoplayer/js/video-player.js
implement logger class and replace `console.log` to it.
> feat: add logger class

- com.unity.renderstreaming/Runtime/Scripts/IRenderStreamingHandler.cs
- com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/FurioosSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/ISignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/SignalingMessage.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Runtime/Scripts/SingleConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/StreamReceiverBase.cs
- com.unity.renderstreaming/Samples~/Example/Gyro/GyroSample.cs
- com.unity.renderstreaming/Samples~/Example/Receiver/ReceiverSample.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
- implement perfect negotiation on `RenderStreamingInternal.cs`
- add test `SendOfferThrowException` and `SwapTransceiver`
Concern
`com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs` 
I think more better class architecture.
Depend https://github.com/Unity-Technologies/UnityRenderStreaming/pull/466
waiting merge to develop branch
> feat: implement perfect negotiation

- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
- com.unity.renderstreaming/Samples~/Example/Receiver/Receiver.unity
> feat: apply multi-resolution about bidirectional and receiver sample scene

- .yamato/meta/environments.yml
- .yamato/upm-ci-renderstreaming-packages.yml
- BuildScripts~/template/remote.sh.template
- BuildScripts~/test_package_mac.sh
Testing for macOS standalone on CI is almost failed so the change fixes this issue.
> chore: Fix scripts for testing macos standalone on CI

- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
- com.unity.renderstreaming/Samples~/Example/Gyro/GyroSample.cs
- com.unity.renderstreaming/Samples~/Example/WebBrowserInput/WebBrowserInput.unity
- Fix exception in the `WebBrowserInput` scene
> fix: Fix exception when disposing WebSocketSignaling instance on Android

- WebApp/public/bidirectional/js/main.js
- WebApp/public/bidirectional/js/peer.js
- WebApp/public/bidirectional/js/sendvideo.js
- WebApp/public/js/signaling.js
- WebApp/public/videoplayer/js/main.js
- WebApp/public/videoplayer/js/video-player.js
- WebApp/src/websocket.ts
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- only change bidirectional sample
- videoplayer is working ( no need change )
Todo: skip test need to fix and enable.
> feat: implement perfectnegotiation on webclient

- WebApp/public/bidirectional/index.html
- WebApp/public/bidirectional/js/main.js
- WebApp/public/bidirectional/js/sendvideo.js
- com.unity.renderstreaming/Runtime/Scripts/WebCamStreamer.cs
- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
> feat: add select video source dropdown for webcam

- .yamato/meta/environments.yml
- .yamato/upm-ci-renderstreaming-packages.yml
- .yamato/upm-ci-webapp.yml
For reducing the usage of GPU instances on the CI process.
> chore: Change the condition of trigger on Yamato CI

- WebApp/public/bidirectional/js/peer.js
- WebApp/public/bidirectional/js/sendvideo.js
- WebApp/public/js/signaling.js
- WebApp/src/signaling.ts
- WebApp/src/websocket.ts
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/Signaling/MockSignaling.cs
- Added check if pair exists
- Fixed behavior when deleting connection
- Removed error in offer / answer
> Fix: webserver error 

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamer.cs
- com.unity.renderstreaming/Runtime/Scripts/Broadcast.cs
- test_webapp.cmd
Fixed `AudioStreamer` to send audio data using the latest WebRTC package.
> fix: Fix AudioStreamer

- com.unity.renderstreaming/Runtime/Scripts/UIController.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/Broadcast.unity
Notice display only if touch device connected
> fix: Add notice about touch control

- com.unity.renderstreaming/Editor/InputSystem/SimplePlayerInputEditor.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputDeviceExtension.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputEditorUserSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputManager.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputRemoting.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/MessageSerializer.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/Receiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/Sender.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/SimplePlayerInput.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystemChannelReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystemChannelSender.cs
- com.unity.renderstreaming/Runtime/Scripts/RemoteInput.cs
- com.unity.renderstreaming/Runtime/Scripts/SimpleCameraController.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/DeltaWithButton.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/SimpleCameraControllerV2.cs
- com.unity.renderstreaming/Samples~/Example/Gyro/GyroSample.cs
- com.unity.renderstreaming/Samples~/Example/Multiplay/MultiplaySample.cs
- com.unity.renderstreaming/Samples~/Example/Multiplay/PlayerController.cs
- com.unity.renderstreaming/Tests/Runtime/InputSystem/InputDeviceExtensionTest.cs
- com.unity.renderstreaming/Tests/Runtime/InputSystem/InputEditorUserSettingsTest.cs
- com.unity.renderstreaming/Tests/Runtime/InputSystem/InputRemotingTest.cs
Add namespace `Unity.RenderStreaming.InputSystem` for collecting codes integrating with **InputSystem**.
> refactor: Add namespace Unity.RenderStreaming.InputSystem

- WebApp/client/public/js/peer.js
- WebApp/client/test/peerconnection.test.js
- WebApp/client/test/peerconnectionmock.js
- checked bidirectional / receiver / videoplayer / multiplay sample
> Fix: add track same behavior on unity side

- com.unity.renderstreaming/Samples~/Example/RenderPipeline/HDRP.unity
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/RenderPipelineSample.cs
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/URP.unity
- fix missing component before `CameraStreamer` and `InputSystemChannelReceiver`
- URP/HDRP related renderstreaming component setting change to same as Broadcast scene.
> Fix: renderpipeline sample

- WebApp/client/public/js/pointercorrect.js
- WebApp/client/public/js/sender.js
- WebApp/client/test/domrect.js
- WebApp/client/test/inputremoting.test.js
- WebApp/client/test/pointercorrect.test.js
- WebApp/client/test/sender.test.js
https://user-images.githubusercontent.com/1132081/142396554-836c2686-d105-4ddc-a46e-0bdf285e0271.mp4
> fix: Fix position of mouse pointer on browser 

- com.unity.renderstreaming/Editor/PropertyDrawers/StreamingSizeDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/StreamingSizeDrawer.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
> feat: Implement streamingsize propety drawer

- com.unity.renderstreaming/Samples~/Example/RenderPipeline/HDRP.unity
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/URP.unity
This is UI fix for sample scenes.
> fix: Add back button in RenderPipeline sample

- WebApp/client/public/multiplay/js/video-player.js
- WebApp/client/public/receiver/js/receiver.js
- WebApp/client/public/videoplayer/js/video-player.js
changed: may invoke `negotiationneeded` method call after signaling start
> Fix: Occurred error on browser when using Websocket

- WebApp/client/public/bidirectional/index.html
- WebApp/client/public/bidirectional/js/main.js
- WebApp/client/public/bidirectional/js/sendvideo.js
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamReceiver.cs
> feat: Add audioinput select on WebApp sample

- WebApp/client/public/receiver/index.html
Correct the path to the Git repo reference on the client index.html.
> doc: Update receiver/index.html

- WebApp/client/jest.setup.js
- WebApp/client/public/bidirectional/css/style.css
- WebApp/client/public/bidirectional/index.html
- WebApp/client/public/bidirectional/js/main.js
- WebApp/client/public/bidirectional/js/sendvideo.js
- WebApp/client/test/peerconnectionmock.js
- WebApp/client/test/resizeobservermock.js
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Samples~/Example/Menu/Menu.unity
- com.unity.renderstreaming/Samples~/Example/Multiplay/Multiplay.cs
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/HDRP.unity
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/RenderPipelineSample.cs
- com.unity.renderstreaming/Samples~/Example/RenderPipeline/URP.unity
- com.unity.renderstreaming/Samples~/Example/Scripts/SceneSelectUI.cs
- Add resolution setting in menu on Unity
- Apply resolution setting to each sample on Unity
- Add resolution setting in Bidirectional sample on WebApp
- Fix web client test
Unity Menu
WebApp Bidirectional sample
> feat: Select video resolution on Unity and WebApp

- WebApp/client/public/js/peer.js
- WebApp/client/public/js/signaling.js
- WebApp/client/public/receiver/js/receiver.js
- WebApp/src/class/httphandler.ts
- WebApp/src/server.ts
- WebApp/src/signaling.ts
- WebApp/test/httphandler.test.ts
- WebApp/test/renderstreaming.postman_collection.json
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/SignalingMessage.cs
- com.unity.renderstreaming/Tests/Runtime/PrivateSignalingTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingTest.cs
Sometimes it puts the error log below when using HTTP mode.
`Failed to set SSL role for the transport.`
> fix: Fixed the issue of signaling process when using HTTP mode

- WebApp/client/public/receiver/index.html
- WebApp/client/public/receiver/js/main.js
This PR is https://github.com/Unity-Technologies/UnityRenderStreaming/pull/693 rebased with current develop branch.
I check, test and review changeset.
Thanks for contributing @CM2Walki
> feat: Webserver pointer lock support

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/IRenderStreamingHandler.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingHandlerBase.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/AudioCodecSelect.cs
- com.unity.renderstreaming/Samples~/Example/Scripts/VideoCodecSelect.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingInternalTest.cs
- com.unity.renderstreaming/Tests/Runtime/SignalingHandlerTest.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs.meta
This PR adds APIs of video/audio streaming configuration in real-time.
```csharp
void VideoStreamSender.SetBitrate(uint bitrate);
void VideoStreamSender.SetFrameRate(float frameRate);
void VideoStreamSender.SetResolutionDown(float scaleFactor);
void AudioStreamSender.SetBitrate(uint bitrate);
```
> feat: Add media streaming configuration APIs 

- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Broadcast/Broadcast.unity
- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
- Fix set scaledown parameter 
- scale down parameter must be greater than 1.0f.
- https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/setParameters
- Fixed processing when bitrate is 0 or null
- Add changing sender parameter UI on Broadcast
> feat: Add sender parameter setting UI in Broadcast sample

- com.unity.renderstreaming/Tests/Editor/EditorTest.cs
- com.unity.renderstreaming/Tests/Editor/EditorTest.cs.meta
- com.unity.renderstreaming/Tests/Editor/RequestJobTest.cs
- com.unity.renderstreaming/Tests/Editor/Unity.RenderStreaming.EditorTests.asmdef
This pull request adds editor tests to check that some static methods are available when Editor mode.
> test: Add editor test to check static method

- com.unity.renderstreaming/Editor/PropertyDrawers/ScaleResolutionDrawer.cs
- com.unity.renderstreaming/Editor/PropertyDrawers/ScaleResolutionDrawer.cs.meta
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
Added the dropdown UI in the `VideoStreamSender` inspector.
This property can control video resolution to reduce the bandwidth.
> feat: Add Scale Resolution Drawer

- com.unity.renderstreaming/CHANGELOG.md
- com.unity.renderstreaming/Editor/PropertyDrawers/BitrateDrawer.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Stats/AssemblyInfo.cs
- com.unity.renderstreaming/Samples~/Example/Stats/AssemblyInfo.cs.meta
- com.unity.renderstreaming/Samples~/Example/Stats/ShowStatsUI.cs
- Update CHANGELOG.
- Make some classes non-public.
- Fix comments
> doc: Update CHANGELOG for 3.1.0-exp.4

- WebApp/client/package-lock.json
- WebApp/client/package.json
- WebApp/package-lock.json
- WebApp/package.json
- pack_webapp.cmd
- pack_webapp.sh
- test_webapp.cmd
- test_webapp.sh
- Ran `npm-check-updates` command to update npm modules
- Add **legacy-peer-deps** option for `npm install` to avoid conflict
> chore: Update npm modules

- .yamato/upm-ci-publish-github-release.yml
- .yamato/upm-ci-template.yml
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
Upgrade the CI image version for publishing binaries of web application.
> chore: Upgrade CI image version for publishing webapp

- com.unity.renderstreaming/Samples~/Example/Broadcast/BroadcastSample.cs
Watch the parameter of videostreamsender, Updated uGUI view when there is a change.
If a value other than the default value is set from Inspector or Script, it will be displayed as Custom.
> fix: Sync setting parameter on Broadcast sample

- com.unity.renderstreaming/Samples~/Example/Receiver/Receiver.unity
Fix the *Signaling URL* parameter `ws;//localhost` to `ws://localhost`.
> fix: Fix the parameter urlSignaling in the Receiver scene

- com.unity.renderstreaming/Samples~/Example/Stats/ShowStatsUI.cs
Needs to merge this fix
https://github.com/Unity-Technologies/com.unity.webrtc/pull/810
> fix: Call GetStats multi times at the same time in StatsUI

- WebApp/package.json
Fixed this issue.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/795
> fix: Fixed missing files to make the packing process for webapp

- com.unity.renderstreaming/Samples~/Example/Broadcast/UIControllerV2.cs
- com.unity.renderstreaming/Samples~/Example/Stats/ShowStatsUI.cs
Fix some exceptions when using Receiver sample.
https://user-images.githubusercontent.com/1132081/209096140-716f8058-29e7-4f9e-b45b-06ee24829907.mp4
> fix: Fix exceptions in Broadcast sample scene

- com.unity.renderstreaming/Samples~/Example/Stats/ShowStatsUI.cs
Sometimes `RTCRtpReceiver.GetStats` and `RTCRtpSender.GetStats` methods take a long time to return on Android.
This PR sets timeout for waiting these methods and updates statistics on the viewer certainly.
> fix: Add timeout for waiting RTCRtpReceiver.GetStats coroutine

- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
This PR adds the audio source type `APIOnly` into `AudioStreamSender` which makes available to pass audio buffer by users. Developers can use `AudioStreamSender.SetData` method for passing buffers as a `NativeArray`.
> fix: Add AudioStreamSender.SetData method to set any audio buffer

- RenderStreaming~/ProjectSettings/EditorBuildSettings.asset
- com.unity.renderstreaming/Editor/RenderStreamingProjectSettingsProvider.cs
- com.unity.renderstreaming/Editor/RenderStreamingSettingBuildProvider.cs
- com.unity.renderstreaming/Editor/RenderStreamingSettingBuildProvider.cs.meta
- com.unity.renderstreaming/Editor/UXML/RenderStreamingProjectSettings.uxml
- com.unity.renderstreaming/Runtime/RenderStreamingSettings.asset
- com.unity.renderstreaming/Runtime/RenderStreamingSettings.asset.meta
- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingSettings.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingSettings.cs
- com.unity.renderstreaming/Tests/Editor/RenderStreamingTest.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingTest.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
- Load settings from Project asset on editor and runtime.
- Add settings to preload assets on build
ToDo: Create UI  for RenderStreaming Settings on Project settings.
> feat: Load Render Streaming  settings

- com.unity.renderstreaming/Editor/PropertyDrawers/SignalingSettingsDrawer.cs
- com.unity.renderstreaming/Editor/RenderStreamingProjectSettingsProvider.cs
- com.unity.renderstreaming/Editor/RenderStreamingSettingsEditor.cs
- com.unity.renderstreaming/Editor/RenderStreamingSettingsEditor.cs.meta
- com.unity.renderstreaming/Editor/UXML/RenderStreamingProjectSettings.uxml
- com.unity.renderstreaming/Runtime/RenderStreamingSettings.asset
- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreamingSettings.cs
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingTest.cs
Create Render Streaming Project Window
On select package default settings when project does not have other settings.
On select package default settings when project has other settings.
On select settings that located under assets.
> feat: Create Render Streaming Project Window

- WebApp/package.json
- WebApp/src/server.ts
Adding CORS * to the signaling server to make it compatible with a client hosted separately.
> Adding CORS support to streaming server

- RenderStreaming~/Packages/manifest.json
- RenderStreaming~/Packages/packages-lock.json
- RenderStreaming~/ProjectSettings/EditorBuildSettings.asset
- com.unity.renderstreaming/package.json
Upgrade version of WebRTC package to **3.0.0-pre.5**.
> fix: Update package dependencies

- com.unity.renderstreaming/Editor/AudioStreamSenderEditor.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
- com.unity.renderstreaming/Samples~/Example/Bidirectional/BidirectionalSample.cs
- com.unity.renderstreaming/Tests/Runtime/StreamingComponentTest.cs
Add loopback flag on Bidirectional sample.
> feat: Add loopback flag on audio stream sender

- com.unity.renderstreaming/Editor/CustomSignalingSettingsEditor.cs
- com.unity.renderstreaming/Editor/RenderStreamingProjectSettings.cs
- com.unity.renderstreaming/Editor/RenderStreamingProjectSettingsProvider.cs
- com.unity.renderstreaming/Editor/RenderStreamingWizard.cs
- com.unity.renderstreaming/Editor/SignalingManagerEditor.cs
- com.unity.renderstreaming/Editor/WebAppDownloader.cs
- com.unity.renderstreaming/Runtime/Scripts/AudioStreamSender.cs
- com.unity.renderstreaming/Runtime/Scripts/Broadcast.cs
- com.unity.renderstreaming/Runtime/Scripts/InputReceiver.cs
- com.unity.renderstreaming/Runtime/Scripts/InputSystem/InputRemoting.cs
- com.unity.renderstreaming/Runtime/Scripts/PeerConnection.cs
- com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/FurioosSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/HttpSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/Signaling/WebSocketSignaling.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingManager.cs
- com.unity.renderstreaming/Runtime/Scripts/SignalingManagerInternal.cs
- com.unity.renderstreaming/Runtime/Scripts/VideoStreamSender.cs
- com.unity.renderstreaming/Tests/Runtime/MockLogger.cs
- com.unity.renderstreaming/Tests/Runtime/MockLogger.cs.meta
- com.unity.renderstreaming/Tests/Runtime/RenderStreamingTest.cs
Description of changes:
- Added configurable logger to Render Streaing to enable users to customize logging for their environment.
- Updated logging inside the package to use the settable logger instead of the built in Unity logging.
How this was tested:
- Tested by running the Render Streaming package tests.
- Ran through the package samples to ensure it's working properly with and without a new logger set.
> feat: Add configurable logger

- WebApp/package-lock.json
- WebApp/package.json
Fix WebApp devDependencies conflict issue
> fix: Fix WebApp devDependencies conflict issue

- com.unity.renderstreaming/Samples~/Example/Bidirectional/Bidirectional.unity
Fixed an error due to different Serialize Version when building.
> fix: Re-save Bidirectional sample scene in 2020.3

- com.unity.renderstreaming/Runtime/Scripts/InputSystem/EmulateInputFieldEvent.cs
> fix: fix inputfield when using textmeshpro

- WebApp/client/public/bidirectional/index.html
- WebApp/client/public/multiplay/index.html
- WebApp/client/public/receiver/index.html
- WebApp/client/public/videoplayer/index.html
Accessing "cdn.polyfill.io" has a security risk. 
https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/
> fix: Remove polyfill

- .yamato/package.metafile
This reverts commit 09bc00b76b20fa26c314a007f33d57761b8d8336.
> revert: "chore: remove CI tests against Unity 2020 (#1014)"
